# Generated by Django 5.1.5 on 2025-01-30 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vote_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('voted_option', models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D'), ('E', 'None of these'), ('F', 'Explain every option in more detail')], max_length=1, null=True)),
            ],
        ),
    ]
